Drawing triangles
NullaWhale/spaceInvaders pull request #15
Opened 2020-09-30 14:31 UTC by nullawhale

2020-09-30 15:03 UTC, andreyrmg requested changes

2020-09-30 15:03 UTC, iam-afk commented on src/Shader.cpp
> +    if (!success) {
На сколько я понимаю, INFO_LOG_LENGTH: the length of the info log, including a null terminator, is returned. If there is an empty info log, zero is returned. Но почему-то потом создается массив на 512 байт, а значение `success` используется в качестве признака успешной компиляции шейдера. Наверно об успехе компиляции стоит всё-таки судить по переменной `result`.

2020-09-30 15:03 UTC, iam-afk commented on src/Shader.cpp
> +    if (!success) {
Аналогично тут.

2020-09-30 15:03 UTC, iam-afk commented on src/Shader.cpp
> +    std::vector<char> programError((success > 1) ? success : 1);
А вот тут мы уже почему-то делаем более менне правильно и вдруг используем `std::vector`...

2020-09-30 15:03 UTC, andreyrmg commented on src/Shader.h
> +GLuint LoadShader(const char *vertex_path, const char *fragment_path);
Раз уж С++, то почему бы не сделать шейдер классом?

2020-09-30 15:03 UTC, andreyrmg commented on src/Main.cpp
> +        GLuint shaderProgram = LoadShader("../shaders/vertexShader.glsl", "../shaders/fragmentShader.glsl");
Очень подозрительные относительные пути.

2020-09-30 15:03 UTC, andreyrmg commented on src/Shader.cpp
> +        std::cout << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << infoLog << std::endl;
Сообщение об ошибке почему-то стало выводится в `std::cout`, хотя прямо в это же файле, в случае неудачи при чтении файла, сообщение об ошибке выводится в `std::cerr`.

2020-10-02 07:39 UTC, andreyrmg requested changes

2020-10-02 07:39 UTC, andreyrmg commented on src/Shader.cpp
> +        std::cerr << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << infoLog << std::endl;
Какой смысл продолжать выполнение, если шейдер не компилируется? Чтобы потом еще увидеть ошибку при линковке?

2020-10-02 07:39 UTC, andreyrmg commented on src/Shader.cpp
> +    GLchar infoLog[512];
Думаешь сообщение компилятора об ошибке не может быть больше 512 байт?

2020-10-02 08:48 UTC, andreyrmg requested changes

2020-10-02 08:48 UTC, andreyrmg commented on src/Shader.cpp
> +
Думаешь сообщение компилятора об ошибке не может быть больше 512 байт?
```suggestion
    GLint result = GL_FALSE;
    GLint infoLogLength;

    glShaderSource(vertShader, 1, &vertShaderSrc, nullptr);
    glCompileShader(vertShader);
    {
        glGetShaderiv(vertShader, GL_COMPILE_STATUS, &result);
        if (result == GL_FALSE) {
            glGetProgramiv(vertShader, GL_INFO_LOG_LENGTH, &infoLogLength);
            std::string infoLog(infoLogLength, 0);
            glGetShaderInfoLog(vertShader, infoLogLength, &infoLogLength, infoLog.data());
            infoLog.resize(infoLogLength);
            std::cerr << "ERROR::SHADER::VERTEX::COMPILATION_FAILED\n" << infoLog << std::endl;
        }
    }

```

2020-10-02 08:48 UTC, andreyrmg commented on src/Shader.cpp
> +
Зачем продолжать, если шейдер все равно не компилируется? Чтобы потом получить еще сообщение об ошибке при линковке?

2020-10-02 08:50 UTC, andreyrmg commented on src/Shader.cpp
> +    }
Аналогично тут.

2020-10-02 08:50 UTC, andreyrmg commented on src/Shader.cpp
> +    }
И тут.

2020-10-02 09:01 UTC, andreyrmg commented on src/Shader.cpp
> +Shader::Shader() = default;
Мне кажется, это должно быть в `Shader.h`

2020-10-02 09:03 UTC, andreyrmg commented on src/Shader.h
> +    static GLuint LoadShader(const char *vertex_path, const char *fragment_path);
Какое отношение этот метод имеет к классу `Shader`? И что вообще олицетворяет класс `Shader`?

2020-10-02 09:03 UTC, andreyrmg commented on src/Vec.h
> +        printf("(%.02f, %.02f, %.02f", x, y, z);
Это не С++.

2021-10-28 13:47 UTC, nullawhale commented on src/Shader.h
> +    static GLuint LoadShader(const char *vertex_path, const char *fragment_path);
Класс Shader содержит методы чтения шейдеров из файла и их загрузку

2021-10-28 14:15 UTC, iam-afk approved these changes

2021-10-29 10:41 UTC, merged

2021-10-29 15:43 UTC, iam-afk reviewed
LGTM